Adding ml-based techniques to SEMAPV
mapping-commons/semantic-mapping-vocabulary pull request #29
Opened 2023-11-08 11:01 UTC by matentzn

Fixes #27 #28 

cc @sven-h @cassiatrojahn

2026-05-26 09:59 UTC, cthoyt commented on semapv-terms.tsv
> +semapv:BoundedPathMatching	bounded path matching	A structural matching process based on the comparison of matched super- and subclasses (paths) of two entities.					semapv:StructuralMatching
not clear what this is. can you please give a concrete example of a piece of software that does this, and of a specific mapping?

2026-05-26 10:02 UTC, cthoyt commented on semapv-terms.tsv
> +semapv:GraphRepresentationLearningBasedMatching	graph representation learning-based matching process	An embedding-based matching process in which matches are identified by comparing learned vector re
This is usually called `graph machine learning`. I've never heard the phrase `graph representation learning` before

2026-05-26 10:04 UTC, cthoyt requested changes
I would like to see concrete references to example software and/or publications where each of the proposed matching processes have been implemented and/or described

2026-05-29 12:25 UTC, cthoyt commented on semapv-terms.tsv
> +semapv:TransformerBasedMatching	transformer-based matching process	An embedding-based matching process that uses transformer models to produce contextual vector representations of entity features for
not a blocking issue, but we are now going to create a shadow concept for the hierarchy of different kinds of ML models here. maybe would be nice if there's a high quality ontology of ML model types to point to. Save this idea for later ;)

2026-05-29 12:28 UTC, cthoyt approved these changes
looks good! let's merge this and nitpick the descriptions in follow-ups

2026-05-29 12:31 UTC, matentzn commented on semapv-terms.tsv
> +semapv:TransformerBasedMatching	transformer-based matching process	An embedding-based matching process that uses transformer models to produce contextual vector representations of entity features for
In principle I agree, but as the blocking discussion with @sven-h  showed, a "Matching" process does more than identify a ML model: it identifies a model and matching decision point (even if its sometimes left a bit vague how the decision is made). Furthermore, there are only a few "general approaches" that lend themselves to matching, so hopefully that will keep the hierarchy tight. 

In principle I agree with the risk of course.

2026-06-02 10:11 UTC, merged